In [1]:
#Importing required libraries
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('ctg_data.csv')
df

b     e  AC  FM  UC  DL  DS  DP  DR   LB  ...  C  D  E  AD  DE  LD  \
0      240   357   0   0   0   0   0   0   0  120  ... -1 -1 -1  -1  -1  -1   
1        5   632   4   0   4   2   0   0   0  132  ... -1 -1 -1   1  -1  -1   
2      177   779   2   0   5   2   0   0   0  133  ... -1 -1 -1   1  -1  -1   
3      411  1192   2   0   6   2   0   0   0  134  ... -1 -1 -1   1  -1  -1   
4      533  1147   4   0   5   0   0   0   0  132  ... -1 -1 -1  -1  -1  -1   
...    ...   ...  ..  ..  ..  ..  ..  ..  ..  ...  ... .. .. ..  ..  ..  ..   
2121  2059  2867   0   0   6   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2122  1576  2867   1   0   9   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2123  1576  2596   1   0   7   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2124  1576  3049   1   0   9   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2125  2796  3415   1   1   5   0   0   0   0  142  ... -1 -1 -1  -1  -1  -1   

      FS  SUSP  CLASS  NSP  
0      1    -1      9    2  
1     -1    -1      6    1  
2     -1    -1      6    1  
3     -1    -1      6    1  
4     -1    -1      2    1  
...   ..   ...    ...  ...  
2121  -1    -1      5    2  
2122  -1    -1      5    2  
2123  -1    -1      5    2  
2124  -1    -1      5    2  
2125  -1    -1      1    1  

[2126 rows x 42 columns]

In [3]:
df.dtypes

b             int64
e             int64
AC            int64
FM            int64
UC            int64
DL            int64
DS            int64
DP            int64
DR            int64
LB            int64
AC.1        float64
FM.1        float64
UC.1        float64
DL.1        float64
DS.1        float64
DP.1        float64
ASTV          int64
MSTV        float64
ALTV          int64
MLTV        float64
Width         int64
Min           int64
Max           int64
Nmax          int64
Nzeros        int64
Mode          int64
Mean          int64
Median        int64
Variance      int64
Tendency      int64
A             int64
B             int64
C             int64
D             int64
E             int64
AD            int64
DE            int64
LD            int64
FS            int64
SUSP          int64
CLASS         int64
NSP           int64
dtype: object

In [4]:
df.isna().sum()

b           0
e           0
AC          0
FM          0
UC          0
DL          0
DS          0
DP          0
DR          0
LB          0
AC.1        0
FM.1        0
UC.1        0
DL.1        0
DS.1        0
DP.1        0
ASTV        0
MSTV        0
ALTV        0
MLTV        0
Width       0
Min         0
Max         0
Nmax        0
Nzeros      0
Mode        0
Mean        0
Median      0
Variance    0
Tendency    0
A           0
B           0
C           0
D           0
E           0
AD          0
DE          0
LD          0
FS          0
SUSP        0
CLASS       0
NSP         0
dtype: int64

In [5]:
df.dropna()

b     e  AC  FM  UC  DL  DS  DP  DR   LB  ...  C  D  E  AD  DE  LD  \
0      240   357   0   0   0   0   0   0   0  120  ... -1 -1 -1  -1  -1  -1   
1        5   632   4   0   4   2   0   0   0  132  ... -1 -1 -1   1  -1  -1   
2      177   779   2   0   5   2   0   0   0  133  ... -1 -1 -1   1  -1  -1   
3      411  1192   2   0   6   2   0   0   0  134  ... -1 -1 -1   1  -1  -1   
4      533  1147   4   0   5   0   0   0   0  132  ... -1 -1 -1  -1  -1  -1   
...    ...   ...  ..  ..  ..  ..  ..  ..  ..  ...  ... .. .. ..  ..  ..  ..   
2121  2059  2867   0   0   6   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2122  1576  2867   1   0   9   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2123  1576  2596   1   0   7   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2124  1576  3049   1   0   9   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2125  2796  3415   1   1   5   0   0   0   0  142  ... -1 -1 -1  -1  -1  -1   

      FS  SUSP  CLASS  NSP  
0      1    -1      9    2  
1     -1    -1      6    1  
2     -1    -1      6    1  
3     -1    -1      6    1  
4     -1    -1      2    1  
...   ..   ...    ...  ...  
2121  -1    -1      5    2  
2122  -1    -1      5    2  
2123  -1    -1      5    2  
2124  -1    -1      5    2  
2125  -1    -1      1    1  

[2126 rows x 42 columns]

In [6]:
df.isna().sum()

b           0
e           0
AC          0
FM          0
UC          0
DL          0
DS          0
DP          0
DR          0
LB          0
AC.1        0
FM.1        0
UC.1        0
DL.1        0
DS.1        0
DP.1        0
ASTV        0
MSTV        0
ALTV        0
MLTV        0
Width       0
Min         0
Max         0
Nmax        0
Nzeros      0
Mode        0
Mean        0
Median      0
Variance    0
Tendency    0
A           0
B           0
C           0
D           0
E           0
AD          0
DE          0
LD          0
FS          0
SUSP        0
CLASS       0
NSP         0
dtype: int64

In [7]:
Features=df.drop('NSP', axis=1)
Label=df['NSP']

In [ ]:
Features.shape

(2126, 41)

In [8]:
Features_T=Features.T
#Features_T.columns= Features_T.iloc[0]
#Features_T.columns

In [10]:
height, width = Features.shape
unique_classes = np.unique(Label)
unique_classes

array([1, 2, 3])

In [11]:
num_classes = len(unique_classes)

scatter_train = np.cov(Features_T)*(height - 1)
scatter_within = 0

In [12]:
for i in range(num_classes):
  class_items = np.flatnonzero(Label == unique_classes[i])
  scatter_within = scatter_within + np.cov(Features_T[class_items]) * (len(class_items)-1)

scatter_between = scatter_train - scatter_within

In [13]:
#Calculating Eigenvalues and Eigenvectors of the covariance matrix

eigen_values, eigen_vectors = np.linalg.eigh(np.linalg.pinv(scatter_within).dot(scatter_between))
        #print(eig_vectors.shape)
        #pc = Features.dot(eig_vectors[:,::-1][:,:self.n_components])

In [14]:
#sort the eigenvalues in descending order
sorted_index = np.argsort(eigen_values)[::-1]
 
sorted_eigenvalue = eigen_values[sorted_index]
#similarly sort the eigenvectors 
sorted_eigenvectors = eigen_vectors[:,sorted_index]
sorted_eigenvectors

array([[ 0.4732847 ,  0.24254814, -0.42273079, ..., -0.4187079 ,
        -0.2494802 , -0.47328548],
       [ 0.52515063, -0.21592378,  0.37658088, ...,  0.37297375,
         0.22209553, -0.52515194],
       [ 0.00600605, -0.0299112 ,  0.05207817, ...,  0.05190328,
         0.03087553, -0.00590249],
       ...,
       [-0.00531018,  0.34093247,  0.10848042, ..., -0.11113122,
         0.33409301, -0.00530762],
       [ 0.0030507 , -0.31402587, -0.08722904, ...,  0.09110984,
        -0.31046093,  0.00304867],
       [-0.0026597 ,  0.08939292,  0.03727651, ..., -0.03699031,
         0.08649941, -0.00265857]])

In [15]:
# select the first n eigenvectors, n is desired dimension
# of our final reduced data.
 
n_components = 30 #you can select any number of components.
eigenvector_subset = sorted_eigenvectors[:,0:n_components]
eigenvector_subset

array([[ 4.73284698e-01,  2.42548139e-01, -4.22730788e-01, ...,
         7.63688917e-10,  1.75092481e-04,  1.37595091e-08],
       [ 5.25150629e-01, -2.15923780e-01,  3.76580879e-01, ...,
        -6.85384611e-10, -1.59906798e-04, -1.25723302e-08],
       [ 6.00604869e-03, -2.99112002e-02,  5.20781660e-02, ...,
        -1.05252713e-09, -7.82502996e-05, -5.56236845e-09],
       ...,
       [-5.31017999e-03,  3.40932473e-01,  1.08480421e-01, ...,
        -1.00779962e-04,  2.07809477e-08, -5.76950176e-04],
       [ 3.05070046e-03, -3.14025872e-01, -8.72290427e-02, ...,
        -1.01895076e-04,  2.00832837e-08, -5.39644962e-04],
       [-2.65969668e-03,  8.93929215e-02,  3.72765087e-02, ...,
         3.94599154e-05, -7.25419056e-09,  1.90989064e-04]])

In [16]:
#Transform the data 
Features_reduced = np.dot(eigenvector_subset.transpose(),Features.transpose()).transpose()
Features_reduced

array([[ 3.00219816e+02, -6.59347495e+01,  1.70109935e+01, ...,
         9.66392784e+01,  9.93696595e-02, -1.28167583e+02],
       [ 3.33399785e+02, -2.29947010e+02,  1.93619922e+02, ...,
         8.89863651e+01,  2.92565897e-02, -1.12945363e+02],
       [ 4.91985410e+02, -2.19317384e+02,  1.76595991e+02, ...,
         8.70908045e+01,  3.98547703e-02, -1.11782724e+02],
       ...,
       [ 2.10824774e+03, -2.76186452e+02,  2.68519032e+02, ...,
         8.52679620e+01, -2.74106294e-03, -1.14437377e+02],
       [ 2.34614499e+03, -3.72528193e+02,  4.39990898e+02, ...,
         8.63243304e+01, -7.52939940e-02, -1.13344794e+02],
       [ 3.11573744e+03, -1.55130642e+02,  6.22744741e+01, ...,
         7.48092146e+01,  7.44569707e-02, -1.07310232e+02]])

In [17]:
LDA_df = pd.DataFrame(Features_reduced)
LDA_df

0           1           2          3         4           5   \
0      300.219816  -65.934750   17.010993  59.124609  5.844682   83.327318   
1      333.399785 -229.947010  193.619922   4.830919  5.698282   63.120979   
2      491.985410 -219.317384  176.595991   4.263816  5.729742   67.714538   
3      819.616540 -249.799361  234.419522   3.914521  5.726301   63.298216   
4      853.750886 -211.771827  165.231600   4.768919  1.620421   71.980959   
...           ...         ...         ...        ...       ...         ...   
2121  2479.152504 -223.564030  163.022568  92.693411  0.325765   92.150053   
2122  2250.567891 -334.604754  370.648322  70.348079  1.251703   60.715813   
2123  2108.247735 -276.186452  268.519032  70.427667  1.285133   74.090073   
2124  2346.144988 -372.528193  439.990898  71.613182  1.165700   51.774940   
2125  3115.737442 -155.130642   62.274474  86.923277 -3.104470  114.572317   

            6         7          8          9   ...        20        21  \
0    -0.203379  1.663506  35.685592 -92.229291  ... -0.002466  6.314596   
1    -1.465711  2.318495   7.011360 -80.785270  ... -0.003551  9.750136   
2    -1.468049  2.360566   8.118046 -81.006216  ... -0.003576  9.668247   
3    -1.438252  2.373348   7.969814 -78.401560  ... -0.003145  7.791075   
4    -0.417423  2.008127   7.557913 -78.254064  ... -0.003217  7.915575   
...        ...       ...        ...        ...  ...       ...       ...   
2121 -1.527899  0.195027  17.040686 -92.713958  ... -0.003337  9.115789   
2122 -1.489938  0.360786   5.282888 -95.854006  ... -0.003296  8.520926   
2123 -1.496605  0.375951   4.852687 -97.233756  ... -0.003306  8.617740   
2124 -1.438497  0.291074   5.283197 -94.068734  ... -0.003286  8.516438   
2125  0.505094 -0.218192  12.716837 -83.710803  ... -0.003132  8.198905   

              22         23        24        25          26         27  \
0    -120.814156  -1.982918  2.632292  1.082313   22.913832  96.639278   
1    -186.095404 -10.672797  0.208781  0.797414  116.502231  88.986365   
2    -184.562987 -10.984091  0.249946  0.806702  113.477589  87.090805   
3    -150.417008 -13.923588  1.374221  0.903092  148.155457  89.197855   
4    -152.368855 -12.007955  1.344114  0.969447  114.884013  89.276588   
...          ...        ...       ...       ...         ...        ...   
2121 -173.514100 -14.094041  0.321803  0.797056  158.297727  70.706889   
2122 -162.727412 -23.273412  1.309286  0.859913  248.717641  84.791373   
2123 -164.366661 -18.131520  1.336912  0.866525  197.032727  85.267962   
2124 -162.697949 -25.742869  1.322362  0.860701  283.661612  86.324330   
2125 -156.001778 -10.251931  0.369455  0.834411  123.420448  74.809215   

            28          29  
0     0.099370 -128.167583  
1     0.029257 -112.945363  
2     0.039855 -111.782724  
3     0.016813 -111.602632  
4     0.039569 -111.899806  
...        ...         ...  
2121  0.032931 -113.126982  
2122 -0.045389 -113.576848  
2123 -0.002741 -114.437377  
2124 -0.075294 -113.344794  
2125  0.074457 -107.310232  

[2126 rows x 30 columns]

# Split Data into Training/Testing

In [39]:
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [20]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(LDA_df, Label, test_size=0.3, random_state=1)

# Decision Tree

In [41]:
from sklearn.tree import DecisionTreeClassifier
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred_train = clf.predict(X_train)

In [46]:
print("Training-set accuracy (in %):",metrics.accuracy_score(y_train, y_pred_train)*100)

Training-set accuracy (in %): 99.93279569892472


In [47]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier(criterion="entropy", max_depth=8)

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy (in %):",metrics.accuracy_score(y_test, y_pred)*100)

Accuracy (in %): 96.08150470219435


# Naive Bayes

In [33]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB() 
gnb.fit(X_train, y_train) 

y_pred_train = gnb.predict(X_train)

print('Training-set accuracy (in %):', metrics.accuracy_score(y_train, y_pred_train)*100)

Training-set accuracy (in %): 84.07258064516128


In [53]:
# making predictions on the testing set 
y_pred = gnb.predict(X_test)

print("Gaussian Naive Bayes model accuracy (in %):", metrics.accuracy_score(y_test, y_pred)*100)

Gaussian Naive Bayes model accuracy (in %): 81.50470219435736


# Random Forest

In [35]:
# importing random forest classifier from assemble module
from sklearn.ensemble import RandomForestClassifier

In [54]:
# creating a RF classifier
rfcl = RandomForestClassifier(n_estimators = 100) 
 
# Training the model on the training dataset
rfcl.fit(X_train, y_train)

y_pred_train = rfcl.predict(X_train)

print('Training-set accuracy (in %):', metrics.accuracy_score(y_train, y_pred_train)*100)

Training-set accuracy (in %): 99.93279569892472


In [55]:
# performing predictions on the test dataset
y_pred = rfcl.predict(X_test)
 
print('Training-set accuracy (in %):', metrics.accuracy_score(y_test, y_pred)*100)

Training-set accuracy (in %): 96.23824451410658


# SVM

In [56]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
svmclf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
svmclf.fit(X_train, y_train)

y_pred_train = svmclf.predict(X_train)

print('Training-set accuracy (in %):', metrics.accuracy_score(y_train, y_pred_train)*100)

Training-set accuracy (in %): 98.18548387096774


In [57]:
#Predict the response for test dataset
y_pred = svmclf.predict(X_test)

# using metrics module for accuracy calculation
print("SVM model accuracy (in %): ", metrics.accuracy_score(y_test, y_pred)*100)

SVM model accuracy (in %):  96.08150470219435
